### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by hikhvar** [bio-routing/bio-rd#103]
Found with #101 
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/bio-routing/bio-rd/protocols/bgp/packet.deserializeMultiProtocolReachNLRI(0xc420018188, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/go-fuzz-build543490251/gopath/src/github.com/bio-routing/bio-rd/protocols/bgp/packet/mp_reach_nlri.go:54 +0x8ae
github.com/bio-routing/bio-rd/protocols/bgp/packet.(*PathAttribute).decodeMultiProtocolReachNLRI(0xc42000c060, 0xc4200c2000, 0x1, 0x0)
	/tmp/go-fuzz-build543490251/gopath/src/github.com/bio-routing/bio-rd/protocols/bgp/packet/path_attributes.go:146 +0x1f8
github.com/bio-routing/bio-rd/protocols/bgp/packet.decodePathAttr(0xc4200c2000, 0xc42005bee5, 0x5181e0, 0x5b6bb0, 0x4d8e60, 0xc42008e520)
	/tmp/go-fuzz-build543490251/gopath/src/github.com/bio-routing/bio-rd/protocols/bgp/packet/path_attributes.go:112 +0xb1e
github.com/bio-routing/bio-rd/protocols/bgp/packet.decodePathAttrs(0xc4200c2000, 0xc420053030, 0xc42005bee5, 0x1, 0x0, 0x0)
	/tmp/go-fuzz-build543490251/gopath/src/github.com/bio-routing/bio-rd/protocols/bgp/packet/path_attributes.go:23 +0x6d
github.com/bio-routing/bio-rd/protocols/bgp/packet.decodeUpdateMsg(0xc4200c2000, 0x1d, 0xc42005bee5, 0x68, 0x12, 0x4d8e60)
	/tmp/go-fuzz-build543490251/gopath/src/github.com/bio-routing/bio-rd/protocols/bgp/packet/decoder.go:63 +0x15f
github.com/bio-routing/bio-rd/protocols/bgp/packet.decodeMsgBody(0xc4200c2000, 0xc4001d8102, 0xc42005bee5, 0x0, 0x5, 0x6, 0xc4200143a0)
	/tmp/go-fuzz-build543490251/gopath/src/github.com/bio-routing/bio-rd/protocols/bgp/packet/decoder.go:36 +0xe7
github.com/bio-routing/bio-rd/protocols/bgp/packet.Decode(0xc4200c2000, 0xc42005bee5, 0xa, 0x45f576, 0x5b52081a)
	/tmp/go-fuzz-build543490251/gopath/src/github.com/bio-routing/bio-rd/protocols/bgp/packet/decoder.go:20 +0x102
github.com/bio-routing/bio-rd/protocols/bgp/packet.Fuzz(0x7f12f6716000, 0x22, 0x200000, 0x4f98c0)
	/tmp/go-fuzz-build543490251/gopath/src/github.com/bio-routing/bio-rd/protocols/bgp/packet/fuzzing.go:22 +0xbd
go-fuzz-dep.Main(0x50ac10)
	/tmp/go-fuzz-build543490251/goroot/src/go-fuzz-dep/main.go:49 +0xad
main.main()
	/tmp/go-fuzz-build543490251/gopath/src/github.com/bio-routing/bio-rd/protocols/bgp/packet/go.fuzz.main/main.go:10 +0x2d
exit status 2
```
Quoted input:
```
	"\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x000\x02\x00" +
	"\x0000a\x0e\b00000000"
```

**Comment by hikhvar** [comment]
Fixed in #105
